## 科学计算的目的
* 收集数据
* 处理数据
* 可视化分析数据

## Python科学计算的基础
Python本身不能很好的执行科学计算的任务，真正可以完成工作的是Python的科学计算扩展模块  
* Numpy
* Scipy
* matplotlib
* Python
* IPython / jupyter notebook / IPython notebook - 辅助工具
* Mayavi
* pandas & seaborn
* sympy
* scikit-learn
* scikit-image

## 交互式的开发环境
IPython / juyter notebook 提供了强大的交互式的界面，基本的使用技巧如下

In [1]:
print("something will be printed!")

something will be printed!


In [3]:
print?    # print?查看介绍，print??可以查看源代码，这一点对于自己的包和模块也是有效的

In [1]:
%run ~/File/Study/Python/StudyPython/MyPythonWheel/mod2div.py

In [3]:
a = 1
%whos

Variable   Type    Data/Info
----------------------------
a          int     1


IPython的基础使用技巧
* !(Linux / Unix Shell Command)
* timeit command 可以计算剪短的语句或者脚本的执行时间
* debug 可以在异常中断之后执行debug程序

## Python语言基础
这里只讨论了开始使用Numpy和Scipy所需的最低要求
以为本人接触Python很长的时间，在这里只记录我的遗漏知识点
* 复数

In [7]:
a = 1.5 + 2j
print(type(a) , a.real , a.imag)

<class 'complex'> 1.5 2.0


* 列表用来容纳数据，可以容纳不同的数据，但是实际上如果是容纳你数组，建议使用numpy中的array速度的更快
* 字符串格式化

In [11]:
print("one : %d , two : %d , three : %s" % (1,2,'3'))

one : 1 , two : 2 , three : 3


* python中的可变对象比如list如果是用切片的方式是原地的改变的

In [15]:
a = [1,2,3]
print(id(a))
a = ['a','b','c']
print(id(a))    # id 改变
a[:] = [1,2,3]
print(id(a))    # id 不变

140623386049864
140623604718472
140623604718472


* 修改正在迭代的列表会发生意想不到的错误，强烈建议不要使用
* 函数参数的默认值在函数定义的时候使用，之后改动是对函数没有影响的
* reload : 对旧的模块修改的话，我们需要重新导入

In [17]:
import os
from imp import reload
reload(os)

<module 'os' from '/usr/lib/python3.5/os.py'>

* 包的信息描述

In [1]:
import os
print(os.__file__)

/usr/lib/python3.5/os.py


## Numpy科学计算核心
* numpy是科学计算的核心，提供贴近硬件执行速度的数组运算
* 内存高效的数据容器，提供快速的数据操作
* len返回第一维的长度,shape返回总共的维数规模元组

In [4]:
import numpy as np
%timeit range(1000)

315 ns ± 22.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
%timeit np.arange(1000)

In [ ]:
a = np.array([1,2,3,4])
print(a.ndim , a.shape , len(a))

In [5]:
np.__version__

'1.12.1'

* 创建numpy数组的方式

In [11]:
np.arange(1,10,2)    # 均匀间隔

array([1, 3, 5, 7, 9])

In [15]:
np.linspace(1,10,6 ,endpoint = True)    # 点分割,endpoint属性决定最后一个边界的点是不是作为结果点

array([  1. ,   2.8,   4.6,   6.4,   8.2,  10. ])

In [18]:
np.ones((3,3))    # 生成制定规模的1元素矩阵

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [20]:
np.zeros((3,3))    # 生成指定规模的0元素矩阵

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [24]:
np.eye(3)    # 生成单位矩阵

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [25]:
np.diag([1,2,3,4])    # diag函数的作用是对于输入的2为矩阵求出赌赢的对角线元素，对与输入的1为向量求出对应的以向量为对角线的矩阵

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [29]:
np.diag(np.diag([1,2,3,4]) , k = 2)    # k的值代表去除对应的斜对角线元素，k > 0从上三角矩阵取，k < 0从下三角矩阵取

array([0, 0])

In [49]:
np.empty((2,3))    # 返回没有初始化过的指定规模的矩阵

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

* 随机数

In [34]:
np.random.rand(2,4)

array([[ 0.96889737,  0.62325707,  0.39419046,  0.47826906],
       [ 0.89115189,  0.22388938,  0.17601448,  0.3717713 ]])

In [36]:
np.random.randn(2,4)

array([[ 0.89138172,  1.51424991,  0.9684666 ,  0.90978274],
       [ 0.35911766,  0.47174982,  0.90199003, -0.46730453]])

In [40]:
np.random.randint(2,3)    # 生成对应的随机整数 [a,b)

2

In [45]:
np.random.seed(12)    # 设置随机种子
print(np.random.randint(2,8))
print(np.random.randint(2,8))
np.random.seed(1)    
print(np.random.randint(2,8))

5
5
7
